CI

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -10,67 +10,99 @@ jobs:
   linux:
     name: Linux
     runs-on: ubuntu-latest
-    container:
-      image: centos:7
     strategy:
       fail-fast: false
       matrix:
         ARCH: [x64]
         include:
           - ARCH: x64
-            PACKAGES: alsa-lib-devel pulseaudio-libs-devel portaudio-devel jack-audio-connection-kit-devel dbus-devel #pipewire-devel
-    defaults:
-      run:
-        shell: bash
+            PACKAGES: libpulse-dev portaudio19-dev libasound2-dev libjack-dev libpipewire-0.3-dev qtbase5-dev libdbus-1-dev
     steps:
       - name: Upgrade git
         run: |
-          sed -i \
-            -e 's/^mirrorlist/#mirrorlist/' \
-            -e 's/^#baseurl/baseurl/' \
-            -e 's/mirror\.centos\.org/vault.centos.org/' \
-            /etc/yum.repos.d/*.repo
-          yum -y install https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm
           yum -y install git
-      - name: Clone repository
-        run: git clone --depth 3 https://github.com/${{ github.repository }}.git .
-      - name: Configure yum
-        run: |
-          yum -y install epel-release
-          yum -y update
-      - name: Install build dependencies
-        run: |
-          yum -y install centos-release-scl
-          sed -i \
-            -e 's/^mirrorlist/#mirrorlist/' \
-            -e 's/^#baseurl/baseurl/' \
-            -e 's/^# baseurl/baseurl/' \
-            -e 's/mirror\.centos\.org/vault.centos.org/' \
-            /etc/yum.repos.d/CentOS-SCLo-scl*.repo
-          yum -y install devtoolset-11-gcc-c++
-          yum -y install cmake3
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 3
       - name: Install OpenAL Soft dependencies
-        run: yum -y install ${{matrix.PACKAGES}}
-        #./autogen.sh -Dprefix=/usr -Dtests=disabled -Dexamples=disabled -Dsession-managers=[] -Dgstreamer=disabled -Davb=disabled -Dv4l2=disabled
-      - name: Build & install recent pipewire
-        run: |
-          pip3 install meson
-          yum -y install ninja-build which libudev-devel
-          git clone --branch 0.3.50 --depth=1 https://gitlab.freedesktop.org/pipewire/pipewire.git
-          cd pipewire
-          source scl_source enable devtoolset-11 || true
-          ./autogen.sh -Dprefix=/usr -Dtests=disabled -Dexamples=disabled -Dgstreamer=disabled -Dv4l2=disabled -Dpipewire-v4l2=disabled
-          make
-          make install
+        run: sudo apt update && sudo apt-get install -qq ${{matrix.PACKAGES}}
       - name: Configure build
         run: |
-          source scl_source enable devtoolset-11 || true
           cmake3 -B build -DALSOFT_REQUIRE_RTKIT=ON -DALSOFT_REQUIRE_ALSA=ON -DALSOFT_REQUIRE_OSS=ON -DALSOFT_REQUIRE_PORTAUDIO=ON -DALSOFT_REQUIRE_PULSEAUDIO=ON -DALSOFT_REQUIRE_JACK=ON -DALSOFT_REQUIRE_PIPEWIRE=ON -DALSOFT_EMBED_HRTF_DATA=YES -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-U_FORTIFY_SOURCE -D_FORTIF=Y_SOURCE=0"
       - name: Build
         run: |
-          source scl_source enable devtoolset-11 || true
           cmake3 --build build --parallel
           strip build/libopenal.so
+      - name: Upload artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: linux-${{matrix.ARCH}}
+          path: build/libopenal.so
+          if-no-files-found: error
+  # linux:
+  #   name: Linux
+  #   runs-on: ubuntu-latest
+  #   container:
+  #     image: centos:7
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       ARCH: [x64]
+  #       include:
+  #         - ARCH: x64
+  #           PACKAGES: alsa-lib-devel pulseaudio-libs-devel portaudio-devel jack-audio-connection-kit-devel dbus-devel #pipewire-devel
+  #   defaults:
+  #     run:
+  #       shell: bash
+  #   steps:
+  #     - name: Upgrade git
+  #       run: |
+  #         sed -i \
+  #           -e 's/^mirrorlist/#mirrorlist/' \
+  #           -e 's/^#baseurl/baseurl/' \
+  #           -e 's/mirror\.centos\.org/vault.centos.org/' \
+  #           /etc/yum.repos.d/*.repo
+  #         yum -y install https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm
+  #         yum -y install git
+  #     - name: Clone repository
+  #       run: git clone --depth 3 https://github.com/${{ github.repository }}.git .
+  #     - name: Configure yum
+  #       run: |
+  #         yum -y install epel-release
+  #         yum -y update
+  #     - name: Install build dependencies
+  #       run: |
+  #         yum -y install centos-release-scl
+  #         sed -i \
+  #           -e 's/^mirrorlist/#mirrorlist/' \
+  #           -e 's/^#baseurl/baseurl/' \
+  #           -e 's/^# baseurl/baseurl/' \
+  #           -e 's/mirror\.centos\.org/vault.centos.org/' \
+  #           /etc/yum.repos.d/CentOS-SCLo-scl*.repo
+  #         yum -y install devtoolset-11-gcc-c++
+  #         yum -y install cmake3
+  #     - name: Install OpenAL Soft dependencies
+  #       run: yum -y install ${{matrix.PACKAGES}}
+  #       #./autogen.sh -Dprefix=/usr -Dtests=disabled -Dexamples=disabled -Dsession-managers=[] -Dgstreamer=disabled -Davb=disabled -Dv4l2=disabled
+  #     - name: Build & install recent pipewire
+  #       run: |
+  #         pip3 install meson
+  #         yum -y install ninja-build which libudev-devel
+  #         git clone --branch 0.3.50 --depth=1 https://gitlab.freedesktop.org/pipewire/pipewire.git
+  #         cd pipewire
+  #         source scl_source enable devtoolset-11 || true
+  #         ./autogen.sh -Dprefix=/usr -Dtests=disabled -Dexamples=disabled -Dgstreamer=disabled -Dv4l2=disabled -Dpipewire-v4l2=disabled
+  #         make
+  #         make install
+  #     - name: Configure build
+  #       run: |
+  #         source scl_source enable devtoolset-11 || true
+  #         cmake3 -B build -DALSOFT_REQUIRE_RTKIT=ON -DALSOFT_REQUIRE_ALSA=ON -DALSOFT_REQUIRE_OSS=ON -DALSOFT_REQUIRE_PORTAUDIO=ON -DALSOFT_REQUIRE_PULSEAUDIO=ON -DALSOFT_REQUIRE_JACK=ON -DALSOFT_REQUIRE_PIPEWIRE=ON -DALSOFT_EMBED_HRTF_DATA=YES -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-U_FORTIFY_SOURCE -D_FORTIF=Y_SOURCE=0"
+  #     - name: Build
+  #       run: |
+  #         source scl_source enable devtoolset-11 || true
+  #         cmake3 --build build --parallel
+  #         strip build/libopenal.so
       # - name: Update dependencies
       #   run: |
       #     yum -y install wget
@@ -93,18 +125,12 @@ jobs:
       #     mkdir build
       #     cd build/
       #     ../configure --prefix=/usr/local/glibc-2.28
-      - name: test
-        run: |
-          source scl_source enable devtoolset-11
-          strings /lib64/libc.so.6 | grep GLIBC
-          strings /lib64/libstdc++.so.6 | grep GLIBCXX
-          strings /lib64/libstdc++.so.6 | grep CXXABI
-      - name: Upload artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: linux-${{matrix.ARCH}}
-          path: build/libopenal.so
-          if-no-files-found: error
+      # - name: Upload artifact
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: linux-${{matrix.ARCH}}
+      #     path: build/libopenal.so
+      #     if-no-files-found: error
 
   linux-cross:
     name: Linux Cross
